### PR TITLE
Adapt harbours to changes in HelenOS/helenos#15

### PR DESCRIPTION
**Pull request by le-jzr**
For clarity, the script is split into several smaller modules.

### CODE REVIEW

**Comment by le-jzr** [comment]
There are some changes to the command line interface. In particular, `update` is removed, since `init` serves its purpose. `hsct.sh init <path>` will look for existing build, `hsct.sh init <path> <profile>` will unconditionally rebuild the profile. The case where one would want to specify an explicit profile, but not want it built, is something I deemed too fringe to pollute the commands with.

All commands which work on a particular package work with existing cache, and never attempt to update it themselves.

**Comment by vhotspur** [comment]
> For clarity, the script is split into several smaller modules.

Actually, it would be better if the split would come before or after as the diff to review would be smaller but okay :-)

> There are some changes to the command line interface. In particular, `update` is removed, since `init` serves its purpose. `hsct.sh init <path>` will look for existing build, `hsct.sh init <path> <profile>` will unconditionally rebuild the profile. The case where one would want to specify an explicit profile, but not want it built, is something I deemed too fringe to pollute the commands with.

Seems reasonable.

> All commands which work on a particular package work with existing cache, and never attempt to update it themselves.

The reason was that if you are fixing something you would be spared the situation when you forget to update the cache and then wonder why the changes does not work.


How is this supposed to be used? Seems I am doing something wrong :-(

```shell
# checkout HelenOS (with the right PR)
make PROFILE=ia32 HANDS_OFF=y
# checkout this PR
mkdir build-ia32 && cd build-ia32
../harbours/hsct.sh init /home/.../helenos/
../harbours/hsct.sh archive zlib
```

Okay, there is certainly some bug in `hsct.sh` as it does not bail out on first error automatically but:

```text
[hsct]: "tar" "xzf" "zlib-1.2.11.tar.gz" 
[hsct]: "env" "CC=i686-pc-linux-gnu-gcc -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include -specs /home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs/gcc.specs -L/home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs -Wl,--whole-archive,-lc,-lmath,--no-whole-archive -Wl,-T,link.ld -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include/cmmzH0" "CFLAGS=" "LD=i686-pc-linux-gnu-ld " "AR=i686-pc-linux-gnu-ar" "RANLIB=i686-pc-linux-gnu-ranlib" "./configure" "--static" 
Using i686-pc-linux-gnu-ar
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
```

```
cat build/zlib/zlib-1.2.11/configure.log 
--------------------
./configure --static
Fri Jan 19 09:39:08 CET 2018
Using i686-pc-linux-gnu-ar
=== ztest31955.c ===
extern int getchar();
int hello() {return getchar();}
===
i686-pc-linux-gnu-gcc -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include -specs /home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs/gcc.specs -L/home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs -Wl,--whole-archive,-lc,-lmath,--no-whole-archive -Wl,-T,link.ld -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include/cmmzH0 -c ztest31955.c
./configure: line 182: i686-pc-linux-gnu-gcc: command not found
... using i686-pc-linux-gnu-gcc -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include -specs /home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs/gcc.specs -L/home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs -Wl,--whole-archive,-lc,-lmath,--no-whole-archive -Wl,-T,link.ld -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include/cmmzH0

Checking for obsessive-compulsive compiler options...
=== ztest31955.c ===
int foo() { return 0; }
===
i686-pc-linux-gnu-gcc -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include -specs /home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs/gcc.specs -L/home/vojta/helenos/reworked-library-export-jzr/build-ia32/libs -Wl,--whole-archive,-lc,-lmath,--no-whole-archive -Wl,-T,link.ld -isystem /home/vojta/helenos/reworked-library-export-jzr/build-ia32/include/cmmzH0 -c ztest31955.c
./configure: line 370: i686-pc-linux-gnu-gcc: command not found
(exit code 127)
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
--------------------

```

Seems to me like `$CROSS_PREFIX` got lost but even setting it explicitly does not help.


By the way, where is `hsct.conf`? It seems to me that you purged it and provided no alternative to specify parallelism or output format. Parallelism is not that needed but output format is required by CI as for the web version we need to upload `tar.gz`.

**Comment by le-jzr** [comment]
> Actually, it would be better if the split would come before or after as the diff to review would be smaller but okay :-)

I'm not sure that's true. Even though a lot of it is reused with minimal changes, I feel like it works too differently to treat it as a simple patch.

> The reason was that if you are fixing something you would be spared the situation when you forget to update the cache and then wonder why the changes does not work.

Sounds reasonable. My reason was that separating the concerns into two independent scripts made it easier for me, but I was also confused as to why have a "cache" at all if the files are pulled from the mainline tree on every build. I worry that one could reasonably run init, start build of the coastline, and continue working on mainline not expecting that the script continues depending on the built files.

> Seems to me like $CROSS_PREFIX got lost but even setting it explicitly does not help.

Hmm, I replaced this with `$HELENOS_CROSS_PATH`, which is supposed to be added to `$PATH`, so that the configure script can find most of the cross tools without needing to tell it specifically. The commands you tried _should_ work, but maybe I forgot something somewhere.

> By the way, where is hsct.conf?

I didn't think it was necessary to have a separate custom configuration file when we're already importing shell variables from `config.sh`. This relates to package operations not touching the cache, so the file isn't getting overwritten like `env.sh` would originally. You can see at the beginning of `hsct_pkg.sh` that all the defaults are set before the file is included.

**Comment by vhotspur** [comment]
> but I was also confused as to why have a "cache" at all if the files are pulled from the mainline tree on every build

The cache is there if you meanwhile rebuild HelenOS for a different architecture and you still want to build packages. Maybe not needed if we have CI.

> > By the way, where is hsct.conf?
> 
> I didn't think it was necessary to have a separate custom configuration file when we're already importing shell variables from `config.sh`. This relates to package operations not touching the cache, so the file isn't getting overwritten like `env.sh` would originally. You can see at the beginning of `hsct_pkg.sh` that all the defaults are set before the file is included.

I am a bit confused now. The packages always use the cache and never try to update it. To update the cache, one needs to call `init` (without parameters). But calling `init` overwrites `config.sh`, right?

**Comment by le-jzr** [comment]
> ./configure: line 182: i686-pc-linux-gnu-gcc: command not found

The only reason for this that I can currently think of, is if you haven't ran the toolchain script in a while, you might possibly still have the installation in the old path. Some time ago, I changed it so that the toolchain is installed under `"$CROSS_PREFIX/<target triple>"` rather than `"$CROSS_PREFIX/<architecture>"`. Mainline scripts still use the old path if necessary, but this branch doesn't, since I've basically forgotten about it. Can you confirm that's the case?

> I am a bit confused now. The packages always use the cache and never try to update it. To update the cache, one needs to call `init` (without parameters). But calling `init` overwrites `config.sh`, right?

Ah, yes, you are right. I did not consider that you might want to call `init` again and keep the changes to the config. Though it should be easy enough to keep the variables that aren't being overwritten.

**Comment by vhotspur** [comment]
> > ./configure: line 182: i686-pc-linux-gnu-gcc: command not found
> 
> The only reason for this that I can currently think of, is if you haven't ran the toolchain script in a while, you might possibly still have the installation in the old path. Some time ago, I changed it so that the toolchain is installed under `"$CROSS_PREFIX/<target triple>"` rather than `"$CROSS_PREFIX/<architecture>"`.

I rebuild the toolchain the day you pushed the modifications. Put perhaps you had  `$CROSS_PREFIX/<target triple>/bin` in your `$PATH`? Because adding that seems to help...


> I did not consider that you might want to call `init` again

Is that the way to update the cache, right (for example, after changing `libposix`)?

**Comment by le-jzr** [comment]
> I rebuild the toolchain the day you pushed the modifications. Put perhaps you had `$CROSS_PREFIX/<target triple>/bin` in your `$PATH`? Because adding that seems to help...

I don't. Besides, the pkg script contains `export PATH="$HELENOS_CROSS_PATH:$PATH"`. Maybe the `config.sh` file is somehow malformed?

**Comment by vhotspur** [comment]
I just re-tried with the following:

```shell
mkdir ~/helenos/reworked-export
cd ~/helenos/reworked-export
git clone git@github.com:HelenOS/helenos.git
cd helenos
git fetch origin pull/15/head:reworked-export
git checkout reworked-export
make PROFILE=ia32 HANDS_OFF=y
cd ..
git clone git@github.com:HelenOS/harbours.git
cd harbours
git fetch origin pull/1/head:reworked-export
git checkout reworked-export
cd ..
mkdir build-ia32
cd build-ia32
../harbours/hsct.sh init ~/helenos/reworked-export/helenos/
```

`config.sh` contains (I only replaced `$HOME` with `~`):

```
HELENOS_ROOT="~/helenos/reworked-export/helenos"
HELENOS_TARGET="i686-pc-linux-gnu"
HELENOS_CFLAGS="-specs ~/helenos/reworked-export/build-ia32/libs/gcc.specs -L~/helenos/reworked-export/build-ia32/libs -Wl,--whole-archive,-lc,-lmath,--no-whole-archive -Wl,-T,link.ld -isystem ~/helenos/reworked-export/build-ia32/include/s1861X"
HELENOS_CROSS_PATH="/i686-pc-linux-gnu/bin"
HSCT_LIB_DIR="~/helenos/reworked-export/build-ia32/libs"
HSCT_INCLUDE_DIR="~/helenos/reworked-export/build-ia32/include"
```

After these steps, zlib compilation fails again.

**Comment by le-jzr** [comment]
Thanks a lot! I know what the problem is now.

**Comment by le-jzr** [comment]
I pushed a new version that should address most of the issues you pointed out. I also put the entire script back into one file, so it should be easier to compare.
I returned an option to set some variables in a configuration file that's not created or modified by the script at all.
I wouldn't be surprised if it's completely broken now, but it somehow survived a test GCC build.

**Comment by vhotspur** [comment]
First of all, it works for me too (GCC on `ia32` at least). Thanks!

I think the following needs to be added to make `config.sh` work as expected:

```diff
diff --git a/hsct.sh b/hsct.sh
index 02ccded..6c5a8d0 100755
--- a/hsct.sh
+++ b/hsct.sh
@@ -328,7 +328,7 @@ hsct_archive() {
 
 hsct_load_config() {
 	# Defaults
-	HSCT_CONFIG=config.sh
+	HSCT_CONFIG=./config.sh
 	HSCT_WGET_OPTS=
 	HSCT_SOURCES_DIR=`pwd`/sources
 	HSCT_FORMAT="tar.xz"
```

I do not like the following simplification:

```
hsct.sh:	HSCT_CC="$HSCT_TARGET-gcc -isystem $HSCT_INCLUDE_DIR $HELENOS_CFLAGS"
```

On one hand it is nice as it reduces number of variables (such as `HSCT_CFLAGS`) needed in the `HARBOUR` files but it breaks the assumption that `CC` contains path to a binary. Probably not a big deal but not the cleanest state either. I would rather see that we properly populate `HSCT_CFLAGS`, `HSCT_CPPFLAGS` etc.

Also, this rather significant change (that `HSCT_CFLAGS` & co. is not set) is not reflected in the `HARBOUR`s that all set `CFLAGS="$HSCT_CFLAGS"`.

What do you think?

Otherwise I quite like it although we are back to rather long lines in Make output ;-)

**Comment by le-jzr** [comment]
My understanding of how build scripts work, is that `CC` contains the name of executable plus any necessary arguments for the target system (which, usually, is none, because you aren't cross-compiling most of the time), and `CFLAGS` is what the user (i.e. the one actually running the script, not the one who wrote it) uses to provide custom flags like `-O4 -fstack-protector-strong -fsanitize=address` and similar. At the very least, the documentation of GNU make explicitly allows this:

>The variables used in implicit rules fall into two classes: those that are names of programs (like CC) and those that contain arguments for the programs (like CFLAGS). (The “name of a program” may also contain some command arguments, but it must start with an actual executable program name.)

...so the assumption that `CC` is just a path to binary is invalid in any case. I also think it's a boon that `CFLAGS` would stay available for outside redefinition, and that the harbour script will not override the project's default flags unnecessarily.

On the other hand, the part where I shunt `HELENOS_CFLAGS` to `CC` instead of `CFLAGS` is maybe a little confusing, isn't it? I feel it deserves at least a bit of commentary.

 > Also, this rather significant change (that `HSCT_CFLAGS` & co. is not set) is not reflected in the `HARBOUR`s that all set `CFLAGS="$HSCT_CFLAGS"`.

Yeah, this is one of those "it doesn't really harm anything except by being ugly, so I'll fix that later" kind of situation. Probably should be resolved before merging.

> Otherwise I quite like it although we are back to rather long lines in Make output ;-)

Nothing a bit of shell script trickery can't address. :-)

**Comment by vhotspur** [comment]
> My understanding of how build scripts work, is that `CC` contains the name of executable plus any necessary arguments for the target system (which, usually, is none, because you aren't cross-compiling most of the time), and `CFLAGS` is what the user (i.e. the one actually running the script, not the one who wrote it) uses to provide custom flags like `-O4 -fstack-protector-strong -fsanitize=address` and similar. At the very least, the documentation of GNU make explicitly allows this:
> 
> >The variables used in implicit rules fall into two classes: those that are names of programs (like CC) and those that contain arguments for the programs (like CFLAGS). (The “name of a program” may also contain some command arguments, but it must start with an actual executable program name.)
> 
> ...so the assumption that `CC` is just a path to binary is invalid in any case.
> I also think it's a boon that `CFLAGS` would stay available for outside redefinition, and that the harbour script will not override the project's default flags unnecessarily.

You are talking about Make. I was referring to `configure` scripts. There, the usual documentation says

```text
Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
```

Although it works (we use `CPP="$HSCT_CC -E"` in several places) I would prefer to keep it separated so the `HARBOUR` files are more explicit. You clearly see that you change the compiler, the C flags and also whether you are adding some extra ones (e.g. `-D_STDIO_H` in GMP).


> On the other hand, the part where I shunt `HELENOS_CFLAGS` to `CC` instead of `CFLAGS` is maybe a little confusing, isn't it? I feel it deserves at least a bit of commentary.

Yeah, eventually in the Wiki. We should shorten the README here anyway as to have instructions in one place only.

**Comment by le-jzr** [comment]
I would prefer if `hsct` created a facade `bin` directory, like `gcc`'s `HARBOUR` does with its `patched-gcc`. Every `HARBOUR` would just assume there is a cross-compiling toolchain available as `{arch}-helenos-{program}` in `$PATH`, and only use `$CFLAGS` for things that differ from the "common base" (i.e. only flags that you would need even if all the tools have full support for a `-helenos` target). There is no reason to complicate things with lots of custom variables, `HARBOUR`s should ideally be future-proof and as simple as technically feasible.

**Comment by le-jzr** [comment]
What do you think about that? `configure` doesn't care if the cross-target is implemented by GCC, or by a shell script facade. Also there's the obvious benefit that this way we can completely switch to a custom HelenOS target without messing with GCC and risking hard-to-debug problems.

**Comment by vhotspur** [comment]
> I would prefer if `hsct` created a facade `bin` directory, like `gcc`'s `HARBOUR` does with its `patched-gcc`. Every `HARBOUR` would just assume there is a cross-compiling toolchain available as `{arch}-helenos-{program}` in `$PATH`, and only use `$CFLAGS` for things that differ from the "common base" (i.e. only flags that you would need even if all the tools have full support for a `-helenos` target). There is no reason to complicate things with lots of custom variables, `HARBOUR`s should ideally be future-proof and as simple as technically feasible.
> 
> What do you think about that? `configure` doesn't care if the cross-target is implemented by GCC, or by a shell script facade. Also there's the obvious benefit that this way we can completely switch to a custom HelenOS target without messing with GCC and risking hard-to-debug problems. 

Generally it sounds okay to me. I have some comments, though.

Could the target really be `{arch}-helenos-{program}`? That would require patching of every `configure` or messing up with autotools.

I hope the shell script facade will not slow things down noticeably as another process would be fired-up for every source file that would only `exec` to the proper GCC.

Looking forward to the patches :-)

**Comment by le-jzr** [comment]
> Could the target really be `{arch}-helenos-{program}`? That would require patching of every `configure` or messing up with autotools.

I don't think it would. Most projects don't need to know the particular OS they are compiling for. I mean, the whole point of configure is to make builds as platform-agnostic as possible, right? And those that do check the operating system, usually do so for a good reason, and that's a hint for us that patching in support for HelenOS will be needed. In any case, I'll do that and we'll see how it works. :)

**Comment by le-jzr** [comment]
@vhotspur Here's the facade patch. As far as messing with autotools is concerned, most packages only need an updated `config.sub`, which is a library file that's just copied to each project without changes, so that makes it very simple. Some more details are in the commit message. Let me know if you have any questions/concerns.

**Comment by vhotspur** [comment]
After I quick scan it looks good. I especially like the removal of so many lines in `HARBOUR`s :-).

I will do a more thorough check next week if you don't mind postponing the merge a bit.

**Comment by le-jzr** [comment]
No problem. :)

**Comment by vhotspur** [comment]
I used the following setup again (using HelenOS master this time):

```shell
mkdir ~/helenos/reworked-export
cd ~/helenos/reworked-export
git clone git@github.com:HelenOS/helenos.git
cd helenos
make PROFILE=ia32 HANDS_OFF=y
cd ..
git clone git@github.com:HelenOS/harbours.git
cd harbours
git fetch origin pull/1/head:reworked-export
git checkout reworked-export
cd ..
mkdir build-ia32
cd build-ia32
../harbours/hsct.sh init ~/helenos/reworked-export/helenos/
```

But I probably misconfigured something as the files in `facade` are missing the triplet and start with dash.

```shell
ls ~/helenos/reworked-export/build-ia32/facade
-ar*  -as*  -cc*  -cpp*  -cxx*  -nm*  -objcopy*  -objdump*  -ranlib*  -strip*
```

Any ideas?

**Comment by le-jzr** [comment]
I'll do a bit of cleanup and get back to you on that.

**Comment by le-jzr** [comment]
Ok, that was my bad. I changed something and forgot to update this part of the script.
It should work now. I also squashed, rebased and cleaned up the pull request, so the diff is as readable as it's ever going to be, I guess. :)

**Comment by le-jzr** [comment]
Hm, apparently Travis doesn't allow `realpath`. I'll sort that out tomorrow.

**Comment by le-jzr** [comment]
@vhotspur Sorry about the delay. Everything seems to be in order now.

**Comment by vhotspur** [comment]
Now it builds okay but the installation seems to fail:

```shell
../harbours/hsct.sh install python2
```

```text
>>> No need to package python2.
>>> Installing...
mkdir: cannot create directory '/uspace': Permission denied
cp: target '/uspace/overlay' is not a directory
```

Why is the `config.guess` script needed? By default, `--build` is guessed by `configure` itself (or by calling the packaged `config.guess`).

How is it with licensing? Now I see two GNU GPL files in the repository while so far the repository was BSD-licensed.

As a minor thing it would be nice if all facade scripts would end with a new-line.

**Comment by le-jzr** [comment]
From [autoconf manual](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html):

>  To ease the transition between 2.13 and its successors, a more complicated scheme is implemented. _Do not rely on the following_, as it will be removed in the near future. 
>
> If you specify `--host`, but not `--build`, when configure performs the first compiler test it tries to run an executable produced by the compiler. If the execution fails, it enters cross-compilation mode. This is fragile. Moreover, by the time the compiler test is performed, it may be too late to modify the build-system type: other tests may have already been performed. Therefore, whenever you specify `--host`, be sure to specify `--build` too. 

In other words, if the first test executable manages to run on the build system (quite possible, if the build and host architecture matches), configure assumes that we _aren't_ cross-compiling unless `--build` is also explicitly set. 

Our own copy of `config.guess` is there because it's not included in some packages, or it's in unique places. This way, we take care of this problem once for all autoconf packages. The two scripts are GPL, but they are completely self-contained and I don't think licence purity outweighs the complexity of alternative solutions. Especially since the the whole repository is means to facilitate building of GNU software (among others).

**Comment by le-jzr** [comment]
Fixed.

**Comment by le-jzr** [comment]
I'm going to go ahead and merge this. Let me know if you notice any issues.

**Pull request merged**
