### PR TITLE
Make use of export-cross and fix facade unbound multiplication

### PR DESCRIPTION
**Pull request by jxsvoboda**
I introduced export-cross makefile target to helenos as a replacement for export-posix. The difference is that export-cross always outputs to $HELENOS_ROOT/uspace/export and is ran as part of the default makefile target, as opposed to export-posix which must be run manually and provided a destination directory. This is used by XCW which can assume that, after helenos has been built, uspace/export directory is populated and so it can immediately read configuration from there. Hsct can use export-cross as well and then export-posix can be removed.

When installing facade tools we would glob * in facade/ and then install arch-xxx into facade/. After a few repeats, we got arch-arch-arch...-xxx and so on. Solved by moving the sources of the tools under facade/src directory (i.e. different directory than where we are installing).

### CODE REVIEW

**Comment by le-jzr** [comment]
Sounds like you are running hsct in the source directory. I never intended for that to be possible.

**Comment by vhotspur** [comment]
> uspace/export directory is populated and so it can immediately read configuration from there. Hsct can use export-cross as well and then export-posix can be removed.

The reason behind the cache dir and the export is that you can prepare build directories for multiple architectures (backed by one HelenOS and one Coastline repository) and test your changes in all of them at once. From my experience (when bringing new package to Coastline), changes in the build process of the ported software happen more often than changes in libposix. Hence this feature.

>> When installing facade tools we would glob * in facade/ and then install arch-xxx into facade/. After a few repeats, we got arch-arch-arch...-xxx and so on
>
> Sounds like you are running hsct in the source directory. I never intended for that to be possible.

Exactly, this is even explicitly mentioned [in the wiki](http://www.helenos.org/wiki/PortingSoftware). I think this commit should be reverted as it only introduces one extra directory layer.

**Comment by jxsvoboda** [comment]
Sorry, my mistake, didn't realize you could build harbours without touching libraries in the helenos workspace. Which commit are you referring to that should be reverted?

I have questions for you. W.r.t. ticket #761 Package for GZX (http://www.helenos.org/ticket/761). I would like to be able toprovide GZX (and other similar software that uses native HelenOS APIs, but are built out-of-tree, e.g. Maurizio's LaiNES port) in a similar way to how we provide the coastline packages so that you could pkg install it / easily find and build or install it

 - Are you OK with providing this via ci.helenos.org like the other coastline packages?
 - What do you think is the best way of integrating it?

I thought I would add a harbour for it. Note that this means:
  - since it requires other libraries (libgui,libhound,libdraw), they would have to be added to the cache dir and the hsct init phase would depend on these being built
  - since this kind of SW uses native HelenOS APIs which are not stable, it means practically these packages would be more tied to the core OS version

So are you OK with providing harbours for this type of package or would you prefer another way of packaging these? (Suggestions?)

**Comment by vhotspur** [comment]
> Which commit are you referring to that should be reverted?

I was referring to the one moving facade scripts.


> I have questions for you. W.r.t. ticket [#761 Package for GZX](http://www.helenos.org/ticket/761). I would like to be able to provide GZX (and other similar software that uses native HelenOS APIs, but are built out-of-tree, e.g. Maurizio's LaiNES port) in a similar way to how we provide the coastline packages so that you could pkg install it / easily find and build or install it
> 
>  - Are you OK with providing this via ci.helenos.org like the other coastline packages?

Definitely, where else? ;-)

>  - What do you think is the best way of integrating it?

My initial thoughts went along the line that we would add something like `shiptype` option that would be either `posix` or `native` and export another set of variables containing paths to XCW etc.


> I thought I would add a harbour for it. Note that this means:
>   - since it requires other libraries (libgui,libhound,libdraw), they would have to be added to the cache dir and the hsct init phase would depend on these being built

Originally, `hsct.sh` copied some libraries (e.g. clui for MSIM) from HelenOSu to its cache; now this is done under `export-posix` for only some of them. I think we should export all libraries – not only a selected subset (in case of naming conflicts, one could copy only the relevant ones aside in a HARBOUR file).

>   - since this kind of SW uses native HelenOS APIs which are not stable, it means practically these packages would be more tied to the core OS version

I do not think there is a big difference to the other (existing) ones.

> So are you OK with providing harbours for this type of package or would you prefer another way of packaging these? (Suggestions?)

Yes, looking forward to the new additions.

I would only like to see a trivial test (for `test-in-vm.py` from CI) for every new application in Coastline to ensure that we can not only compile but also run everything we have there.

**Pull request closed without merging**
